#!/bin/bash

apt-get update
apt-get install -y python-software-properties python-dev python-pip python3-dev python3-pip
add-apt-repository ppa:neovim-ppa/unstable
apt-get update
apt-get install -y neovim
pip install --user neovim
