#!/bin/bash


SRC=$(dirname $(readlink -e $0))

# vim-plug: Simple plugin manager to download directly from github instead of saving all our plugins locally
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [ ! -d "$HOME/.vimrc" ]; then
    ln -s "$SRC/vimrc" "$HOME/.vimrc"
fi
