#!/bin/bash

apt-get update
apt-get install -y software-properties-common python3-software-properties python3-dev python3-pip
add-apt-repository ppa:neovim-ppa/unstable
apt-get update
apt-get install -y neovim
pip3 install --upgrade pip
pip3 install --user neovim
