#!/bin/sh

SRC=$(dirname $(readlink -e $0))

mkdir -p "$HOME/.config/nvim"

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -f "$HOME/.config/nvim/init.vim" ]; then
    ln -s "$SRC/init.vim" "$HOME/.config/nvim/init.vim"
fi
