#!/bin/sh

SRC=$(dirname $(readlink -e $0))

mkdir -p "$HOME/.config/nvim"

if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -d "$HOME/.vim" ]; then
    ln -s "$SRC/.vim" "$HOME/.vim"
fi

if [ ! -f "$HOME/.config/nvim/init.vim" ]; then
    ln -s "$SRC/init.vim" "$HOME/.config/nvim/init.vim"
fi

if [ ! -f "$HOME/.bash_settings" ]; then
    ln -s "$SRC/.bash_settings" "$HOME/.bash_settings"
fi

echo "source \"$HOME/.bash_settings\"" >> "$HOME/.bashrc"

if [ ! -f "$HOME/.gitconfig" ]; then
    ln -s "$SRC/.gitconfig" "$HOME/.bash_settings"
fi
